### ISSUE TITLE
Add SBUL and Key Capsule entities

### ISSUE THREAD

**Issue by rjwut** [DeviateFish/ingress-model-viewer#27]
IMV.Entities.Inventory currently lacks entries for the SoftBank Ultra Link and the Key Capsule.

**Comment by DeviateFish** [comment]
Entities are going to be deprecated soon.  I added the drawables for Key Capsule in #26, and I'll make sure to add in the ULA entries, as well.

**Comment by DeviateFish** [comment]
Looks like I still need to fix the rendering of the ULA, though.

**Comment by DeviateFish** [comment]
Done in #26
