### ISSUE TITLE
bower install error

### ISSUE THREAD

**Issue by jrichardsz** [DeviateFish/ingress-model-viewer#38]
Hi. Thanks for your time.

After this success commands: 
npm install -g grunt-cli
npm install -g bower
npm install

This command **bower install**
throws this  error:

`
bower                     invalid-meta for:C:\..\..\ingress-model-viewer-master\bower.json`
`
bower                     invalid-meta The "main" field cannot contain minified files
`

My environment is:
windows 7
node v6.11.1

Thanks in advance.

**Comment by DeviateFish** [comment]
Sorry about these, the README is out of date.  This project no longer uses both Bower and Grunt.  It now uses webpack for building, with dependencies all installed via npm.

Closed by #40
