### ISSUE TITLE
grunt starting error

### ISSUE THREAD

**Issue by jrichardsz** [DeviateFish/ingress-model-viewer#39]
Hi. Thanks for your time.

After install commands:
npm install -g grunt-cli
npm install -g bower
npm install
bower install **(error)** link to issue [https://github.com/DeviateFish/ingress-model-viewer/issues/38](https://github.com/DeviateFish/ingress-model-viewer/issues/38)

The last command from your readme:  **grunt**
throws this error
`grunt-cli: The grunt command line interface (v1.2.0)`
`Fatal error: Unable to find local grunt.`
`If you're seeing this message, grunt hasn't been installed locally to
your project. `

My environment is:
windows 7
node v6.11.1

Thanks in advance.

**Comment by DeviateFish** [comment]
Sorry about these, the README is out of date.  This project no longer uses both Bower and Grunt.  It now uses webpack for building, with dependencies all installed via npm.

Closed by #40
